In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from pathlib import Path

In [2]:
df = pd.read_csv("../data/processed/cleaned_data.csv")

print(df.shape)

df.head()

(283726, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 283726 entries, 0 to 283725
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    283726 non-null  float64
 1   V1      283726 non-null  float64
 2   V2      283726 non-null  float64
 3   V3      283726 non-null  float64
 4   V4      283726 non-null  float64
 5   V5      283726 non-null  float64
 6   V6      283726 non-null  float64
 7   V7      283726 non-null  float64
 8   V8      283726 non-null  float64
 9   V9      283726 non-null  float64
 10  V10     283726 non-null  float64
 11  V11     283726 non-null  float64
 12  V12     283726 non-null  float64
 13  V13     283726 non-null  float64
 14  V14     283726 non-null  float64
 15  V15     283726 non-null  float64
 16  V16     283726 non-null  float64
 17  V17     283726 non-null  float64
 18  V18     283726 non-null  float64
 19  V19     283726 non-null  float64
 20  V20     283726 non-null  float64
 21  V21     283726 non-null  float64
 22  V22     283726 non-null  float64
 23  V23     283726 non-null  float64
 24  V24     283726 non-null  float64
 25  V25     283726 non-null  float64
 26  V26     283726 non-null  float64
 27  V27     283726 non-null  float64
 28  V28     283726 non-null  float64
 29  Amount  283726 non-null  float64
 30  Class   283726 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.1 MB

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Time,283726.0,94811.077600,47481.047891,0.000000,54204.750000,84692.500000,139298.000000,172792.000000
V1,283726.0,0.005917,1.948026,-56.407510,-0.915951,0.020384,1.316068,2.454930
V2,283726.0,-0.004135,1.646703,-72.715728,-0.600321,0.063949,0.800283,22.057729
V3,283726.0,0.001613,1.508682,-48.325589,-0.889682,0.179963,1.026960,9.382558
V4,283726.0,-0.002966,1.414184,-5.683171,-0.850134,-0.022248,0.739647,16.875344
V5,283726.0,0.001828,1.377008,-113.743307,-0.689830,-0.053468,0.612218,34.801666
V6,283726.0,-0.001139,1.331931,-26.160506,-0.769031,-0.275168,0.396792,73.301626
V7,283726.0,0.001801,1.227664,-43.557242,-0.552509,0.040859,0.570474,120.589494
V8,283726.0,-0.000854,1.179054,-73.216718,-0.208828,0.021898,0.325704,20.007208
V9,283726.0,-0.001596,1.095492,-13.434066,-0.644221,-0.052596,0.595977,15.594995
V10,283726.0,-0.001441,1.076407,-24.588262,-0.535578,-0.093237,0.453619,23.745136
V11,283726.0,0.000202,1.018720,-4.797473,-0.761649,-0.032306,0.739579,12.018913
V12,283726.0,-0.000715,0.994674,-18.683715,-0.406198,0.139072,0.616976,7.848392
V13,283726.0,0.000603,0.995430,-5.791881,-0.647862,-0.012927,0.663178,7.126883
V14,283726.0,0.000252,0.952215,-19.214325,-0.425732,0.050209,0.492336,10.526766
V15,283726.0,0.001043,0.914894,-4.498945,-0.581452,0.049299,0.650104,8.877742
V16,283726.0,0.001162,0.873696,-14.129855,-0.466860,0.067119,0.523512,17.315112
V17,283726.0,0.000170,0.842507,-25.162799,-0.483928,-0.065867,0.398972,9.253526
V18,283726.0,0.001515,0.837378,-9.498746,-0.498014,-0.002142,0.501956,5.041069
V19,283726.0,-0.000264,0.813379,-7.213527,-0.456289,0.003367,0.458508,5.591971
V20,283726.0,0.000187,0.769984,-54.497720,-0.211469,-0.062353,0.133207,39.420904
V21,283726.0,-0.000371,0.723909,-34.830382,-0.228305,-0.029441,0.186194,27.202839
V22,283726.0,-0.000015,0.724550,-10.933144,-0.542700,0.006675,0.528245,10.503090
V23,283726.0,0.000198,0.623702,-44.807735,-0.161703,-0.011159,0.147748,22.528412
V24,283726.0,0.000214,0.605627,-2.836627,-0.354453,0.041016,0.439738,4.584549
V25,283726.0,-0.000232,0.521220,-10.295397,-0.317485,0.016278,0.350667,7.519589
V26,283726.0,0.000149,0.482053,-2.604551,-0.326763,-0.052172,0.240261,3.517346
V27,283726.0,0.001763,0.395744,-22.565679,-0.070641,0.001479,0.091208,31.612198
V28,283726.0,0.000547,0.328027,-15.430084,-0.052818,0.011288,0.078276,33.847808
Amount,283726.0,88.472687,250.399437,0.000000,5.600000,22.000000,77.510000,25691.160000
Class,283726.0,0.001667,0.040796,0.000000,0.000000,0.000000,0.000000,1.000000

In [5]:
fig = px.pie(
    names=["Legitimate", "Fraud"],
    values=df["Class"].value_counts().sort_index(),
    title="Transaction Distribution"
)

fig.show()

In [6]:
fraud = df["Class"].value_counts(normalize=True) * 100

print(fraud)

Class
0    99.83329
1     0.16671
Name: proportion, dtype: float64